"$schema" = 'https://starship.rs/config-schema.json'

palette = 'main'

format = """
[](fg:#394260)\
[](bg:#059669 fg:#394260)\
[](bg:#059669 fg:primary)\
$directory\
[](fg:primary bg:#059669)\
[](fg:#059669 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$cmd_duration\
[ ](fg:#1d2230)\
\n$character\u0020"""

[character]
format = '[❯](bold primary)'

[directory]
style = "fg:#090c0c bg:primary"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:primary bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:primary bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:primary bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:primary bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:primary bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:primary bg:#212736)]($style)'

[cmd_duration]
min_time = 500
format = '[  $duration ](fg:#a0a9cb bg:#1d2230)'

[palettes.main]
primary = "#34d399" 
