Augroup = vim.api.nvim_create_augroup("UserConfig", {clear = true})
require("configs")
require("configs/keymaps")
require("addons/statusline")
require("addons/autocmd")
require("addons/terminal")
require("plugins/git")
require("plugins/fzf")
require("plugins/lsp")
require("plugins/cosmetic")
require("plugins/explorer")
require("plugins/mini")
require("plugins/obsidian")
require("plugins/whichkey")
require("addons/vimpack")
